### ISSUE TITLE
0xc000007b error

### ISSUE THREAD

**Issue by imbug0** [kuma-dayo/RuntimeDumper#1]
When I try to modify to `version.dll` and open the game again, the prompt is: 
`This application was unable to start correctly (0xc000007b). Click OK to close the application.`
Whether download dll from release or compile it (as Release) myself.

**Comment by kuma-dayo** [comment]
Try using [v1.1.0](https://github.com/kuma-dayo/RuntimeDumper/releases/tag/v1.1.0). It should fix the problem.

**Comment by imbug0** [comment]
It's working!
